# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import pgl_rpc_pb2 as pgl__rpc__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pgl_rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PglRemoteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChoosePlan = channel.unary_unary(
                '/pgl_rpc.PglRemote/ChoosePlan',
                request_serializer=pgl__rpc__pb2.ChoosePlanRequest.SerializeToString,
                response_deserializer=pgl__rpc__pb2.ChoosePlanResponse.FromString,
                _registered_method=True)


class PglRemoteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChoosePlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PglRemoteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChoosePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.ChoosePlan,
                    request_deserializer=pgl__rpc__pb2.ChoosePlanRequest.FromString,
                    response_serializer=pgl__rpc__pb2.ChoosePlanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pgl_rpc.PglRemote', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pgl_rpc.PglRemote', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PglRemote(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChoosePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pgl_rpc.PglRemote/ChoosePlan',
            pgl__rpc__pb2.ChoosePlanRequest.SerializeToString,
            pgl__rpc__pb2.ChoosePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
