# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pgl_rpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pgl_rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpgl_rpc.proto\x12\x07pgl_rpc\"\"\n\x11\x43hoosePlanRequest\x12\r\n\x05plans\x18\x01 \x03(\t\"/\n\x12\x43hoosePlanResponse\x12\x19\n\x11\x63hosen_plan_index\x18\x01 \x01(\x05\".\n\x1a\x43\x61rdinalityEstimateRequest\x12\x10\n\x08rel_opts\x18\x01 \x03(\t\"<\n\x1b\x43\x61rdinalityEstimateResponse\x12\x1d\n\x15\x63\x61rdinality_estimates\x18\x01 \x03(\x03\x32\xb4\x01\n\tPglRemote\x12\x45\n\nChoosePlan\x12\x1a.pgl_rpc.ChoosePlanRequest\x1a\x1b.pgl_rpc.ChoosePlanResponse\x12`\n\x13\x43\x61rdinalityEstimate\x12#.pgl_rpc.CardinalityEstimateRequest\x1a$.pgl_rpc.CardinalityEstimateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pgl_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHOOSEPLANREQUEST']._serialized_start=26
  _globals['_CHOOSEPLANREQUEST']._serialized_end=60
  _globals['_CHOOSEPLANRESPONSE']._serialized_start=62
  _globals['_CHOOSEPLANRESPONSE']._serialized_end=109
  _globals['_CARDINALITYESTIMATEREQUEST']._serialized_start=111
  _globals['_CARDINALITYESTIMATEREQUEST']._serialized_end=157
  _globals['_CARDINALITYESTIMATERESPONSE']._serialized_start=159
  _globals['_CARDINALITYESTIMATERESPONSE']._serialized_end=219
  _globals['_PGLREMOTE']._serialized_start=222
  _globals['_PGLREMOTE']._serialized_end=402
# @@protoc_insertion_point(module_scope)
